### ISSUE TITLE
'Report any bugs' text gives 404

### ISSUE THREAD

**Issue by claremacrae** [GuiMar10/monochroYOU#1]
Congrats on getting your theme approved!

I noticed the README says:

> Report any bugs at the GitHub repo: GuiMar10/maerial-you-for-obsidian

When I manually make a URL out of that, I get a 404:

https://github.com/GuiMar10/maerial-you-for-obsidian

When I add the missing `t` to `maerial` the link does work:

https://github.com/GuiMar10/material-you-for-obsidian

And it redirects to:

https://github.com/GuiMar10/monochroYOU

Whilst fixing the typo, to help users of your theme in Obsidian, it might be worth replacing the current text with the full URL so they can click on it...

**Comment by GuiMar10** [comment]
Thank you! Fixed ❤️
